### ISSUE TITLE
Merge of Triplicate Samples

### ISSUE THREAD

**Issue by VictorBorin** [jtamames/SqueezeM#2]
First of all, thank you for the tool. It's making my work easier.

I have a doubt. My samples have triplicates and I inform the SqueezeM in the metadata file what's samples is. Which method does SqueezeM use to merge the triplicates results? Because they give us only one result of raw counts, RPKM, and coverage. Is it an average?
I read your paper about the tool and the item 2 of methods, showing a database creation. How can I access this method?

Thank you very much

**Comment by fpusan** [comment]
Dear Victor,
Please check https://github.com/jtamames/SqueezeMdb for the code and instructions required for database creation.

Best,
Fernando

**Comment by VictorBorin** [comment]
Thank you Fernando for the information. I will try.

All the best,
Victor

**Comment by fpusan** [comment]
Make sure to check the last Readme at https://github.com/jtamames/SqueezeMdb.
We now include more detailed instructions for working with the application.
